### ISSUE TITLE
Segfault with B::Hooks::AtRuntime due to lack of PUSHSTACKi()

### ISSUE THREAD

**Issue by iabyn** [mauzo/B-Hooks-AtRuntime#2]
B::Hooks::AtRuntime can SEGV due to deeply nested sub calls from the hook triggering a context stack reallocation. The correct fix is for the XS module to temporary push a new set set of stacks before calling the hook sub.

See the thread at https://www.perlmonks.org/?node_id=11145964, in particular my reproduction, diagnosis and proposed solution: https://www.perlmonks.org/?node_id=11145995.

Note that my reproduction only works on perls that have been specially built with -DDEBUGGING - this enables assertions, one of which the reproducing code triggers on recent perls.

**Comment by mauzo** [comment]
Thank you for the report, and for the detailed analysis. I have fixed this with v8.

I have very little time for Perl development these days (not my choice...); is there any chance you might be willing to take over maintenance of this module?
